
package com.dmitry.lab1j2ee;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MotorbikeWebService", targetNamespace = "http://lab1J2ee.dmitry.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MotorbikeWebService {


    /**
     * 
     * @return
     *     returns java.util.List<com.dmitry.lab1j2ee.Motorbike>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllBikes", targetNamespace = "http://lab1J2ee.dmitry.com/", className = "com.dmitry.lab1j2ee.GetAllBikes")
    @ResponseWrapper(localName = "getAllBikesResponse", targetNamespace = "http://lab1J2ee.dmitry.com/", className = "com.dmitry.lab1j2ee.GetAllBikesResponse")
    @Action(input = "http://lab1J2ee.dmitry.com/MotorbikeWebService/getAllBikesRequest", output = "http://lab1J2ee.dmitry.com/MotorbikeWebService/getAllBikesResponse")
    public List<Motorbike> getAllBikes();

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param personRequest
     * @return
     *     returns java.util.List<com.dmitry.lab1j2ee.Motorbike>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFind", targetNamespace = "http://lab1J2ee.dmitry.com/", className = "com.dmitry.lab1j2ee.GetFind")
    @ResponseWrapper(localName = "getFindResponse", targetNamespace = "http://lab1J2ee.dmitry.com/", className = "com.dmitry.lab1j2ee.GetFindResponse")
    @Action(input = "http://lab1J2ee.dmitry.com/MotorbikeWebService/getFindRequest", output = "http://lab1J2ee.dmitry.com/MotorbikeWebService/getFindResponse")
    public List<Motorbike> getFind(
        @WebParam(name = "personRequest", targetNamespace = "")
        String personRequest,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

}
