
package com.dmitry.lab1j2ee;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonWebService", targetNamespace = "http://lab1J2ee.dmitry.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonWebService {


    /**
     * 
     * @return
     *     returns java.util.List<com.dmitry.lab1j2ee.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllPersons", targetNamespace = "http://lab1J2ee.dmitry.com/", className = "com.dmitry.lab1j2ee.GetAllPersons")
    @ResponseWrapper(localName = "getAllPersonsResponse", targetNamespace = "http://lab1J2ee.dmitry.com/", className = "com.dmitry.lab1j2ee.GetAllPersonsResponse")
    @Action(input = "http://lab1J2ee.dmitry.com/PersonWebService/getAllPersonsRequest", output = "http://lab1J2ee.dmitry.com/PersonWebService/getAllPersonsResponse")
    public List<Person> getAllPersons();

    /**
     * 
     * @param personRequest
     * @return
     *     returns java.util.List<com.dmitry.lab1j2ee.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFind", targetNamespace = "http://lab1J2ee.dmitry.com/", className = "com.dmitry.lab1j2ee.GetFind")
    @ResponseWrapper(localName = "getFindResponse", targetNamespace = "http://lab1J2ee.dmitry.com/", className = "com.dmitry.lab1j2ee.GetFindResponse")
    @Action(input = "http://lab1J2ee.dmitry.com/PersonWebService/getFindRequest", output = "http://lab1J2ee.dmitry.com/PersonWebService/getFindResponse")
    public List<Person> getFind(
        @WebParam(name = "personRequest", targetNamespace = "")
        String personRequest);

}
